---
name: Provision EKS
on:
  push:
    branches:
      - 'add/action-provision-eks'
    tags:
      - 'release-*'
      - 'destroy-*'

jobs:
  eks-provision:
    name: Provision EKS cluster in AWS
    if: ${{ startsWith(github.ref, 'refs/tags/release-') || startsWith(github.ref, 'refs/heads/add') }}
    runs-on: terraform-provisioner

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform -chdir=./eks init
      
      - name: Terraform Plan
        run: terraform -chdir=./eks plan

      # - name: Terraform Apply   # The terraform state file is store in the runner's host
      #   run: terraform -chdir=./eks -state=/home/ubuntu/terraform.tfstate apply --auto-approve

  alb-ingress-controller-provision:
    name: Provision ALB Ingress Controller
    if: ${{ startsWith(github.ref, 'refs/tags/release-') || startsWith(github.ref, 'refs/heads/add') }}
    needs:
      - eks-provision
    runs-on: terraform-provisioner

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform -chdir=./eks/alb init

      - name: Terraform Plan
        run: terraform -chdir=./eks/alb plan