# Workflow to provision and manage resources in AWS EKS and ALB Ingress Controller

# Trigger the workflow on push events for tags starting with 'release-' or 'destroy-'
on:
  push:
    tags:
      - 'release-*'
      - 'destroy-*'

jobs:
  # Job to provision EKS cluster
  eks-provision:
    name: Provision EKS cluster in AWS
    # Run the job only for specific branch patterns
    if: ${{ startsWith(github.ref, 'refs/tags/release-') || startsWith(github.ref, 'refs/heads/add') }}
    runs-on: terraform-provisioner

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform -chdir=./eks init
      
      - name: Terraform Plan
        run: terraform -chdir=./eks plan

      - name: Terraform Apply   # Apply the Terraform configuration
        run: terraform -chdir=./eks apply -state=/home/ubuntu/doct-3345-tfstate/terraform-eks.tfstate --auto-approve

  # Job to configure Kube Configuration File
  kube-config-setup:
    name: Configuring Kube Configuration File to Access EKS API
    # Run the job only for specific branch patterns and after the eks-provision job
    if: ${{ startsWith(github.ref, 'refs/tags/release-') || startsWith(github.ref, 'refs/heads/add') }}
    needs:
      - eks-provision
    runs-on: terraform-provisioner

    steps:
      - name: Configuring Kube Configuration using AWS CLI
        env:
          CLUSTER_NAME: cbd3345-eks-cluster   # Update this variable if needed
        run: KUBECONFIG=~/.kube/eks_k8s_config aws eks update-kubeconfig --region ca-central-1 --name ${{ env.CLUSTER_NAME }}

  # Job to provision ALB Ingress Controller
  alb-ingress-controller-provision:
    name: Provision ALB Ingress Controller
    # Run the job only for specific branch patterns and after kube-config-setup job
    if: ${{ startsWith(github.ref, 'refs/tags/release-') || startsWith(github.ref, 'refs/heads/add') }}
    needs:
      - kube-config-setup
    runs-on: terraform-provisioner

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform -chdir=./eks/alb init

      - name: Terraform Plan
        run: terraform -chdir=./eks/alb plan -state=/home/ubuntu/doct-3345-tfstate/terraform-alb.tfstate

      - name: Terraform Apply   # Apply the Terraform configuration for ALB Ingress Controller
        run: KUBE_CONFIG_PATH=~/.kube/eks_k8s_config terraform -chdir=./eks/alb apply -state=/home/ubuntu/doct-3345-tfstate/terraform-alb.tfstate --auto-approve

  # Job to destroy ALB Ingress Controller
  alb-destroy:
    name: Destroy ALB Ingress Controller
    # Run the job only for tags starting with 'destroy-'
    if: startsWith(github.ref, 'refs/tags/destroy-')
    runs-on: terraform-provisioner

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform -chdir=./eks/alb init

      - name: Terraform Plan (with destroy option)    # Plan the destruction of ALB Ingress Controller
        run: KUBE_CONFIG_PATH=~/.kube/eks_k8s_config terraform -chdir=./eks/alb plan -state=/home/ubuntu/doct-3345-tfstate/terraform-alb.tfstate -destroy 

      - name: Terraform Destroy   # Destroy ALB Ingress Controller
        run: KUBE_CONFIG_PATH=~/.kube/eks_k8s_config terraform -chdir=./eks/alb destroy -state=/home/ubuntu/doct-3345-tfstate/terraform-alb.tfstate --auto-approve

  # Job to destroy EKS Cluster
  eks-destroy:
    name: Destroy EKS Cluster
    # Run the job only for tags starting with 'destroy-'
    if: startsWith(github.ref, 'refs/tags/destroy-')
    needs: 
      - alb-destroy
    runs-on: terraform-provisioner

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform -chdir=./eks init

      - name: Terraform Plan (with destroy option)    # Plan the destruction of EKS Cluster
        run: terraform -chdir=./eks plan -state=/home/ubuntu/doct-3345-tfstate/terraform-eks.tfstate -destroy

      - name: Terraform Destroy   # Destroy EKS Cluster
        run:  terraform -chdir=./eks destroy -state=/home/ubuntu/doct-3345-tfstate/terraform-eks.tfstate --auto-approve